### ISSUE TITLE
Advent of star_data module alters file paths

### ISSUE THREAD

**Issue by jschwab** [wmwolf/MesaScript#7]
In r12778, `star_job_controls.inc` is now in `star_data/private/`.  Rather than doing a version check, the simplest thing is probably to try `star_data` and then if not found, look in `star` (or vice-versa).

**Comment by jschwab** [comment]
I saw there was already at least one version-based check, so I implemented such a check in #8.

**Comment by wmwolf** [comment]
Pulled in and pushed to rubygems as version v0.2.0.
