### ISSUE TITLE
gem version doesn't match git tags

### ISSUE THREAD

**Issue by jschwab** [wmwolf/MesaScript#9]
I was momentarily confused about which version of `MesaScript` I was using as the repository has tags like `1.0.2`, but the current gem version is `0.1.9`.  Should these match?

**Comment by wmwolf** [comment]
I have never actually tried to use git tags, so I'm not sure what those mean. I'll review it before pushing the new version out, though.

**Comment by wmwolf** [comment]
Turns out I completely forgot I was making formal releases, and it also turns out I had no idea what I was doing. Newest release has version matching the rubygems version, and I may go back to fixe the old ones, too, so we don't have confusion down the line.

**Comment by wmwolf** [comment]
Three years later and there is at last a new release. I think I have the hang of this now. Closing, and I'll just deal with the confusion of the "1.0" tags if and when we get there.
